# Generated by Django 6.0.6 on 2026-06-19 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Update Date'),
        ),
    ]
