# Generated by Django 6.0.6 on 2026-07-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
