# Generated by Django 6.0.6 on 2026-06-26 15:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_productvariant_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attribute',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=400, verbose_name='attribute'),
        ),
    ]
