# Generated by Django 6.0.6 on 2026-07-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Site Title')),
                ('description', models.CharField(max_length=160, verbose_name='Site Description')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Logo')),
                ('favicon', models.ImageField(upload_to='logo/', verbose_name='Favicon')),
                ('email', models.EmailField(max_length=254, verbose_name='Site Email')),
                ('about_text', models.TextField(verbose_name='About Text')),
                ('privacy_policy', models.TextField(verbose_name='Privacy Policy')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LI', 'Landline'), ('MP', 'Mobile Phone')], default='LI', max_length=2, verbose_name='Phone Type')),
                ('use_for', models.CharField(choices=[('MGT', 'Management'), ('SIS', 'Site Support'), ('SAS', 'Sales Support')], default='SAS', max_length=3, verbose_name='Use For')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='core.sitesettings')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('province', models.CharField(max_length=50, verbose_name='Province')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.sitesettings')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INS', 'Instagram'), ('TEL', 'Telegram'), ('WHT', 'WhatsApp')], default='INS', max_length=3, verbose_name='Name')),
                ('url', models.URLField(max_length=254, verbose_name='Url')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='core.sitesettings')),
            ],
        ),
    ]
