# Generated by Django 6.0.6 on 2026-07-18 09:22

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('province', models.CharField(max_length=50, verbose_name='Province')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=11, validators=[accounts.validators.validate_phone_number], verbose_name='Phone Number')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.TextField(blank=True, help_text='To display on the home page of the site', verbose_name='Short Description')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_for', models.CharField(max_length=50, verbose_name='Use For')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('icon', models.ImageField(max_length=50, upload_to='icons/', verbose_name='Icon')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Site Title')),
                ('description', models.CharField(max_length=160, verbose_name='Site Description')),
                ('logo', models.ImageField(max_length=50, upload_to='logo/', verbose_name='Logo')),
                ('favicon', models.ImageField(max_length=50, upload_to='logo/', verbose_name='Favicon')),
                ('email', models.EmailField(max_length=254, verbose_name='Site Email')),
                ('answer_hours', models.CharField(blank=True, max_length=50, verbose_name='Answering Hours')),
                ('copyright', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('url', models.URLField(max_length=254, verbose_name='Url')),
                ('icon', models.ImageField(max_length=50, upload_to='icons/', verbose_name='Icon')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
    ]
