# Generated by Django 6.0.6 on 2026-07-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is Primary'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is Primary'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='icon',
            field=models.ImageField(blank=True, max_length=50, upload_to='icons/', verbose_name='Icon'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('is_primary',), name='only_one_primary_address'),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('is_primary',), name='only_one_primary_phone'),
        ),
    ]
