# Generated by Django 6.0.6 on 2026-07-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_is_primary_phonenumber_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
