# Generated by Django 6.0.6 on 2026-07-11 06:55

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sitesettings_sitesetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=11, validators=[accounts.validators.validate_phone_number], verbose_name='Phone Number')),
                ('message', models.CharField(max_length=100, verbose_name='Message')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS Sent')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='site_settings',
            new_name='site_setting',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='site_settings',
            new_name='site_setting',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='site_settings',
            new_name='site_setting',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='answer_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name='Answering Hours'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='privacy_policy',
            field=models.TextField(blank=True, verbose_name='Privacy Policy'),
        ),
    ]
