# Generated by Django 6.0.6 on 2026-07-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.ImageField(blank=True, max_length=50, upload_to='icons/', verbose_name='Icon'),
        ),
    ]
