# Generated by Django 6.0.6 on 2026-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sociallink_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('CO', 'Contact'), ('AB', 'About'), ('PR', 'Privacy Policy')], default='CO', max_length=2, unique=True, verbose_name='Page Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default=' ', max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
