# Generated by Django 6.0.6 on 2026-07-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_page_slug_page_page_type_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('CO', 'Contact'), ('AB', 'About'), ('PR', 'Privacy Policy'), ('CA', 'Catalog')], max_length=2, unique=True, verbose_name='Page Type'),
        ),
        migrations.AlterField(
            model_name='page',
            name='short_description',
            field=models.TextField(blank=True, help_text='To display on the home page.', verbose_name='Short Description'),
        ),
    ]
