# Generated by Django 6.0.6 on 2026-07-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_page_meta_description_page_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='short_description',
            field=models.TextField(blank=True, help_text='Optional short text for places like the Home page.', verbose_name='Short Description'),
        ),
    ]
