# Generated by Django 6.0.6 on 2026-07-20 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_page_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='description',
            new_name='site_description',
        ),
        migrations.RenameField(
            model_name='sitesetting',
            old_name='title',
            new_name='site_title',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(default=' ', max_length=50, upload_to='site/', verbose_name='Home Hero Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_text',
            field=models.TextField(default=' ', verbose_name='Home Hero Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default=' ', max_length=200, verbose_name='Home Hero Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_description',
            field=models.CharField(default=' ', max_length=160, verbose_name='Home Meta Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_title',
            field=models.CharField(default=datetime.datetime(2026, 7, 20, 18, 40, 46, 509188, tzinfo=datetime.timezone.utc), max_length=70, verbose_name='Home Meta Title'),
            preserve_default=False,
        ),
    ]
