# Generated by Django 6.0.6 on 2026-08-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_description_sitesetting_site_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
    ]
