# Generated by Django 6.0.6 on 2026-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_contactmessage_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(fields=('use_for', 'phone_number'), name='unique_use_for_phone_number'),
        ),
    ]
