# Generated by Django 6.0.6 on 2026-06-26 15:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description'),
        ),
    ]
