# Generated by Django 6.0.6 on 2026-06-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_summary_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='datetime_update',
            new_name='datetime_updated',
        ),
    ]
