# Generated by Django 6.0.6 on 2026-07-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='Features',
            new_name='features',
        ),
    ]
